-- MySQL Script generated by MySQL Workbench
-- 08/05/15 20:28:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ck_onto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ck_onto` ;

-- -----------------------------------------------------
-- Schema ck_onto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ck_onto` DEFAULT CHARACTER SET utf8 ;
USE `ck_onto` ;

-- -----------------------------------------------------
-- Table `class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class` ;

CREATE TABLE IF NOT EXISTS `class` (
  `id_class` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `class` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`id_class`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 270
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `class_UNIQUE` ON `class` (`class` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `class_class_relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class_class_relationship` ;

CREATE TABLE IF NOT EXISTS `class_class_relationship` (
  `id_rel` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_superclass` INT(11) NOT NULL COMMENT '',
  `id_subclass` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rel`)  COMMENT '',
  CONSTRAINT `fk_subclass`
    FOREIGN KEY (`id_subclass`)
    REFERENCES `class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_superclass`
    FOREIGN KEY (`id_superclass`)
    REFERENCES `class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 273
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_superclass_idx` ON `class_class_relationship` (`id_superclass` ASC)  COMMENT '';

CREATE INDEX `fk_subclass_idx` ON `class_class_relationship` (`id_subclass` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `keyphrase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keyphrase` ;

CREATE TABLE IF NOT EXISTS `keyphrase` (
  `id_keyphrase` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `keyphrase` VARCHAR(200) CHARACTER SET 'latin1' NOT NULL COMMENT '',
  `stemmed_keyphrase` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_keyphrase`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 7814
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `id_keyphrase` ON `keyphrase` (`id_keyphrase` ASC)  COMMENT '';

CREATE UNIQUE INDEX `text` ON `keyphrase` (`keyphrase` ASC)  COMMENT '';

CREATE UNIQUE INDEX `text_2` ON `keyphrase` (`keyphrase` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `class_keyphrase_relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class_keyphrase_relationship` ;

CREATE TABLE IF NOT EXISTS `class_keyphrase_relationship` (
  `id_rel` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_keyphrase` INT(11) NOT NULL COMMENT '',
  `id_class` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rel`)  COMMENT '',
  CONSTRAINT `fk_class`
    FOREIGN KEY (`id_class`)
    REFERENCES `class` (`id_class`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keyphrase`
    FOREIGN KEY (`id_keyphrase`)
    REFERENCES `keyphrase` (`id_keyphrase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8027
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_keyphrase_idx` ON `class_keyphrase_relationship` (`id_keyphrase` ASC)  COMMENT '';

CREATE INDEX `fk_class_idx` ON `class_keyphrase_relationship` (`id_class` ASC)  COMMENT '';

CREATE INDEX `fk_keyphrase_index` ON `class_keyphrase_relationship` (`id_keyphrase` ASC)  COMMENT '';

CREATE INDEX `fk_class_index` ON `class_keyphrase_relationship` (`id_class` ASC)  COMMENT '';

CREATE INDEX `fk_keyphrase_index1` ON `class_keyphrase_relationship` (`id_keyphrase` ASC)  COMMENT '';

CREATE INDEX `fk_class_index1` ON `class_keyphrase_relationship` (`id_class` ASC)  COMMENT '';

CREATE INDEX `fk_keyphrase_index2` ON `class_keyphrase_relationship` (`id_keyphrase` ASC)  COMMENT '';

CREATE INDEX `fk_class_index2` ON `class_keyphrase_relationship` (`id_class` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationship` ;

CREATE TABLE IF NOT EXISTS `relationship` (
  `id_relationship` INT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `value` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`id_relationship`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `keyphrase_keyphrase_relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keyphrase_keyphrase_relationship` ;

CREATE TABLE IF NOT EXISTS `keyphrase_keyphrase_relationship` (
  `id_rel` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_keyphrase1` INT(11) NOT NULL COMMENT '',
  `id_keyphrase2` INT(11) NOT NULL COMMENT '',
  `id_relationship` INT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rel`)  COMMENT '',
  CONSTRAINT `fk_keyphrase1`
    FOREIGN KEY (`id_keyphrase1`)
    REFERENCES `keyphrase` (`id_keyphrase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_keyphrase2`
    FOREIGN KEY (`id_keyphrase2`)
    REFERENCES `keyphrase` (`id_keyphrase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship`
    FOREIGN KEY (`id_relationship`)
    REFERENCES `relationship` (`id_relationship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2440
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_keyphrase1_idx` ON `keyphrase_keyphrase_relationship` (`id_keyphrase1` ASC)  COMMENT '';

CREATE INDEX `fk_keyphrase2_idx` ON `keyphrase_keyphrase_relationship` (`id_keyphrase2` ASC)  COMMENT '';

CREATE INDEX `fk_relationship_idx` ON `keyphrase_keyphrase_relationship` (`id_relationship` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
